repository = "termapps/dotsync"

exclude = ["aur"]

[homebrew]
repository = "termapps/homebrew-tap"

[aur_bin]
name = "dotsync"

[scoop]
repository = "termapps/scoop-bucket"

[nix]
repository = "termapps/nixpkgs"

lockfile = false
path     = "%n.nix"

[npm]
name = "@termapps/dotsync"
